Обновил отчет
spbu-se/mag_practices_2021-2023 pull request #19
Opened 2021-12-30 21:20 UTC by RexTremendaeMajestatis

2021-12-31 05:56 UTC, dluciv requested changes
Павел, спасибо, надо *Отчёт о про прохождении учебной (ознакомительной) практики*, как у Вас в расписании. Или просто *Отчёт о прохождении практики*.

2022-03-24 12:48 UTC, dluciv requested changes
Павел, Вы же с ПИ?

Тогда у Вас "Учебная (ознакомительная) практика". А не курсовая работа и не магистерская диссертация. Сделайте пожалуйста нормальный титульник уже...

2022-04-13 09:35 UTC, TheGadji commented
[Ахмедов Г.О_Отчёт.pdf](https://github.com/spbu-se/mag_practices_2021-2023/files/8480128/_.pdf)
[Ахмедов Г.О_Презентация .pptx](https://github.com/spbu-se/mag_practices_2021-2023/files/8480129/_.pptx)

2022-05-29 14:06 UTC, dluciv commented
Ясно понятно. Пришлось титульник поправить самому...

2022-05-29 14:06 UTC, closed without merging