Отчет Турсунова
spbu-se/mag_practices_2021-2023 pull request #74
Opened 2023-05-11 02:31 UTC by tursunova

2023-05-11 10:12 UTC, dluciv requested changes
И отзыв плиз

2023-05-12 02:44 UTC, tursunova commented
Готово, отзыв загрузила

2023-05-12 17:42 UTC, tursunova commented
> И отзыв плиз
Готово

2023-05-13 20:28 UTC, dluciv approved these changes

2023-05-13 20:28 UTC, merged